"""Hand-written SQL migration runner. Idempotent.

The plan rejects autogenerated migrations. This module scans
`db/migrations/*.sql`, sorted ascending by filename, and applies each
file that has not already been recorded in the `applied_migrations`
ledger table. Running the script repeatedly is a no-op.
"""

from __future__ import annotations

import logging
import os
import sqlite3

logger = logging.getLogger(__name__)

MIGRATIONS_DIR = os.path.join(os.path.dirname(__file__), "migrations")


def _ensure_applied_table(conn: sqlite3.Connection) -> None:
    """Create the ledger table if it does not exist.

    The ledger is itself defined in 0001_init.sql, but we create a minimal
    version here first so the runner can self-bootstrap on a fresh DB.
    """
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS applied_migrations (
            filename TEXT PRIMARY KEY,
            applied_at TEXT NOT NULL DEFAULT (datetime('now'))
        );
        """
    )


def _already_applied(conn: sqlite3.Connection, filename: str) -> bool:
    cur = conn.execute(
        "SELECT 1 FROM applied_migrations WHERE filename = ? LIMIT 1;",
        (filename,),
    )
    return cur.fetchone() is not None


def _record_applied(conn: sqlite3.Connection, filename: str) -> None:
    conn.execute(
        "INSERT INTO applied_migrations (filename) VALUES (?);",
        (filename,),
    )


def apply_pending(conn: sqlite3.Connection) -> list[str]:
    """Apply every un-applied .sql file in db/migrations, sorted ascending.

    Returns the list of filenames applied this run (empty list when up to date).
    Each file is run as a single executescript() so it can contain multiple
    statements and pragmas.
    """
    _ensure_applied_table(conn)

    if not os.path.isdir(MIGRATIONS_DIR):
        logger.warning("migrations dir not found: %s", MIGRATIONS_DIR)
        return []

    files = sorted(
        f for f in os.listdir(MIGRATIONS_DIR)
        if f.endswith(".sql")
    )
    applied: list[str] = []
    for fname in files:
        if _already_applied(conn, fname):
            continue
        path = os.path.join(MIGRATIONS_DIR, fname)
        with open(path, "r", encoding="utf-8") as fh:
            sql = fh.read()
        logger.info("applying migration: %s", fname)
        conn.executescript(sql)
        _record_applied(conn, fname)
        applied.append(fname)
        print(f"applied migration: {fname}")
    if not applied:
        print("no pending migrations")
    return applied
